name: Deploy to AWS ECS

on:
  push:
    branches:
      - newtest  # Triggers deployment when code is pushed to the final branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Changed to match BigBank AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          ECR_REPO_URI=http://241533127016.dkr.ecr.us-east-2.amazonaws.com/bigbank-ecr-repository
          docker build -t $ECR_REPO_URI:latest .
          echo "ECR_REPO_URI=$ECR_REPO_URI" >> $GITHUB_ENV

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push ${{ env.ECR_REPO_URI }}:latest

      - name: Deploy New Image to ECS
        run: |
          aws ecs update-service --cluster bigbank-ecs-cluster --service bigbank-node-service --force-new-deployment
